# Path to checkpoint file or a directory containing checkpoint files. Passing
# a directory will only work if there is also a file named 'checkpoint' which
# lists the available checkpoints in the directory. It will not work if you
# point to a directory with just a copy of a model checkpoint: in that case,
# you will need to pass the checkpoint path explicitly.
CHECKPOINT_PATH="/YOURPATH/im2txt/Pretrained-Show-and-Tell-model/model.ckpt-2000000"

# Vocabulary file generated by the preprocessing script.
VOCAB_FILE="/YOURPATH/im2txt/Pretrained-Show-and-Tell-model/word_counts.txt"

# JPEG image file to caption.
IMAGE_FILE="/YOURPATH/im2txt/test-images/honeybread.jpeg"


# Build the inference binary.
bazel build -c opt im2txt/run_inference

# Run inference to generate captions.
bazel-bin/im2txt/run_inference \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --vocab_file=${VOCAB_FILE} \
  --input_files=${IMAGE_FILE}
